config/routes.rb
Rails.application.routes.draw do
  resources :gifs
  resources :users, only: [:index, :show]
  resources :user_entries
  resources :categories
  resources :topics
  root to: "categories#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :topics
  # has_many :user_entries, through: :topics
  # has_many :users, through: :topics
  # has_many :gifs, through: :topics
end

app/models/gif.rb
class Gif < ApplicationRecord
  belongs_to :user_entry
  # belongs_to :topic, through: :user_entry
  # belongs_to :user, through: :user_entry
  # belongs_to :category, through: :user_entry
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :category
  has_many :user_entries
  has_many :users, through: :user_entries
  # has_many :gifs, through: :user_entries
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_entries
   has_many :topics, through: :user_entries
   has_many :categories, through: :user_entries
end

app/models/user_entry.rb
class UserEntry < ApplicationRecord
  has_many :gifs
  belongs_to :user
  belongs_to :topic
  # belongs_to :category, through: :topic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  # byebug
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  # def new
  #   @category = Category.new
  # end
  # #
  # def create
  #   @category = Category.create(params[:id])
  #   redirect_to @category
  # end
  # #
  #
  # #
  # def edit
  #   @category = Category.find(params[:id])
  # end
  # #
  # def update
  #   @category = Category.find(params[:id])
  #   @category.update(category_params)
  #   redirect_to @category
  # end
  # #
  # # def destroy
  # # end
  #
  # def category_params
  #       params.require(:category).permit(:name)
  # end

end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController

  def index
  end

  def new
  end

  def create
  end

  def show
    @gif = Gif.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    @category = @topic.category
  end

  def new
    @topic = Topic.new
  end
  #
  def create

    @topic = Topic.create(topic_params)
    redirect_to topics_path
  end
  #

  #
  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.update(topic_params)
    redirect_to topics_path
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to @topic
  end

  private

  def topic_params
    params.require(:topic).permit(:category_id,:name, :description, :link)
  end

end

app/controllers/user_entries_controller.rb
class UserEntriesController < ApplicationController
  def index
    @user_entries = UserEntry.all
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    
  end

  def new
  end

  def create
  end



  def edit
  end

  def update
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/gifs_helper.rb
module GifsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/user_entries_helper.rb
module UserEntriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<div class="container">
  <h1>Welcome to: Flatiron Community Notes!</h1>
  <h2>Pick a Catagory</h2>

  <%@categories.each do |category|%>
  <h2><%=link_to category.name, category_path(category.id)%></h2>
  <%end%>
</div>

app/views/categories/show.html.erb
<b>Topics:</b> <%=@category.name%>
<ul>
<%@category.topics.each do |topic|%>
<b><%=link_to topic.name,  topic_path(topic)%></b>
<%=topic.description%> </br>
<%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlatironCommunityNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/topics/edit.html.erb
<%= form_for(@topic) do |f| %>
  Your
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%f.label :select%>
  <%= f.collection_select(:category_id, Category.all, :id, :name)%>
  <%= f.submit %>
<% end %>

app/views/topics/index.html.erb
<h1>Ruby</h1>
<%@topics.each do |topic|%>
<ul>
<li><%=link_to topic.name, topic_path(topic)%></li>
</ul>
<%end%>

app/views/topics/new.html.erb
<%= form_for(@topic) do |f| %>
  Your
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :link %>
  <%= f.text_field :link %>
  <%f.label :select%>
  <%= f.collection_select(:category_id, Category.all, :id, :name)%>
  <%= f.submit %>
<% end %>

app/views/topics/show.html.erb
<h1><%=@topic.name%></h1> </br>
<b>Description: </b> <%=@topic.description%></br>
<%=@topic.link%>
<b>Category: </b><%= link_to @category.name, category_path(@category)%>

<%= link_to "Delete", @topic, method: :delete%>
<!-- <%=link_to "edit", @topic, method: :edit%> -->
<%= link_to 'Edit Topic', edit_topic_path(@topic) %>

app/views/users/index.html.erb
<%@users.each do |user|%>
<%=link_to user.name, user_path(user)%></br>
<%=user.bio%></br>
<%end%>

app/views/users/show.html.erb
<h1>This is <%= @user.name %> page</h1>

<%=@user.bio%>
<%@user.topics.each do |topic|%>

<ul>
<li><%=topic.name%> </li></br>
<%=topic.description%></br>

</Ul>
<%end%>